### ISSUE TITLE
Error thrown by update_property_database on is_distance_transitive

### ISSUE THREAD

**Issue by yirkajk** [math1um/objects-invariants-properties#509]
When I run update_property_database, it throws an error when attempting to calculate is_distance_transtitive.
The error never occurs when I just run is_distance_transitive on its own without the update function. But, once I've had this error while updating, any time I call is_distance_transitive I get a similar error.

I've run this on CoCalc and on our own local server.
I've tried running this for a couple different graphs, each time just a single graph at a time. I've also tried running it for all properties and for just is_distance_transitive. And, I've tried reloading everything and seeing if the order of any prior commands has an effect; I can't find one.

My guess is the use of Sage's `Set` instead of `set` causes problems. is_distance_transitive is the only property to use `Set` right now.
Tomorrow, I will try rewriting the function using `set` and see if that fixes the issue.
@nvcleemp Do you know of any likely problems using Sage's `Set` while threading?

```
update_property_database(properties, [graphs.PetersenGraph()])

Process Process-8:
Traceback (most recent call last):
  File "/ext/sage/sage-8.1/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/ext/sage/sage-8.1/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 265, in compute_property_value
  File "<string>", line 2014, in is_distance_transitive
  File "sage/misc/cachefunc.pyx", line 2016, in sage.misc.cachefunc.CachedMethodCaller.__call__ (build/cythonized/sage/misc/cachefunc.c:10855)
    w = self._instance_call(*args, **kwds)
  File "sage/misc/cachefunc.pyx", line 1892, in sage.misc.cachefunc.CachedMethodCaller._instance_call (build/cythonized/sage/misc/cachefunc.c:10306)
    return self.f(self._instance, *args, **kwds)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/groups/perm_gps/permgroup.py", line 1291, in orbit
    result = self._gap_().Orbit(point, action).sage()
  File "sage/structure/sage_object.pyx", line 749, in sage.structure.sage_object.SageObject._gap_ (build/cythonized/sage/structure/sage_object.c:7056)
    return self._interface_(G)
  File "sage/structure/sage_object.pyx", line 725, in sage.structure.sage_object.SageObject._interface_ (build/cythonized/sage/structure/sage_object.c:6573)
    X = I(s)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/interface.py", line 282, in __call__
    return cls(self, x, name=name)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/expect.py", line 1383, in __init__
    self._name = parent._create(value, name=name)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/interface.py", line 478, in _create
    self.set(name, value)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/gap.py", line 1363, in set
    self._eval_line(cmd, allow_use_file=True)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/gap.py", line 740, in _eval_line
    return self._eval_line_using_file(line)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/gap.py", line 1417, in _eval_line_using_file
    return Expect._eval_line_using_file(self, line)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/expect.py", line 782, in _eval_line_using_file
    s = self._eval_line(self._read_in_file_command(tmp_to_use), allow_use_file=False, restart_if_needed=False)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/gap.py", line 742, in _eval_line
    expect_eof= (self._quit_string() in line))
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/sage/interfaces/gap.py", line 607, in _execute_line
    x = E.expect_list(self._compiled_full_pattern)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/pexpect/spawnbase.py", line 355, in expect_list
    return exp.expect_loop(timeout)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/pexpect/expect.py", line 98, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 441, in read_nonblocking
    if not self.isalive():
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 666, in isalive
    alive = ptyproc.isalive()
  File "/ext/sage/sage-8.1/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/ext/sage/sage-8.1/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 23, in _wrap_ptyprocess_err
    raise ExceptionPexpect(*e.args)
ExceptionPexpect: isalive() encountered condition where "terminated" is 0, but there was no child process. Did someone else call waitpid() on our process?
Computation of is_distance_transitive for Petersen graph failed!
```

**Comment by yirkajk** [comment]
This same error continued even once I removed all references to `Sets` and used `set` instead.
Taking a closer look at the error output, the errors are thrown by gap.py. This is the package that implements the automorphism group.

**Comment by math1um** [comment]
graphs.DiamondGraph()

throws an errorr:
`IndexError: list index out of range`

as do the following graphs with order<30 in graph_objects:
 ['Diamond Graph', 'p3', 'p4', 'ce55', 'k4e2split', 'LozTof10']

it would be worth investigating our distance transitivity algorithm.

**Comment by thenealon** [comment]
I bet this is a vertex label issue, and doing a g.relabel() at the
beginning of the algorithm would fix it (diamond in particular has
non-interference vertex labels).  I'm away from my computer and can't test
this today.

**Comment by yirkajk** [comment]
I spent some time on this. There are several bugs in how I coded it.

The problem with most of those graphs was I checked if `sameDistPairs` was None, which was wrong. I changed it to length >= 2.
The problem with LozTof10 was that `LozTof10.diameter() == +Infinity`. So, I changed how our for loop iterates distances.
I haven't commited anything yet. Still have to do:

- [ ] The definition of distance transitive requires (a,b) and (u,v) to be disjoint. Need to modify code to do this. For example, right now Tutte12Cage returns True even though it should be false.
- [ ] The async issue with update_property_database.

For the async issue, I think it's the automorphism package, since the error statements reference gap.py. Neal, I'm going to email you about this.

```
def is_distance_transitive(g):
    """
    True if all distinct a,b,u,v satisfy dist(a,b) = dist(u,v) => there is an automorphism sending a->u and b->v

    sage: is_distance_transitive(graphs.Tutte12Cage())
    False
    sage: is_distance_transitive(graphs.FosterGraph())
    True
    """
    from itertools import combinations
    dist_dict = g.distance_all_pairs()
    auto_group = g.automorphism_group()

    for d in g.distances_distribution():
        sameDistPairs = []
        for (u,v) in combinations(g.vertices(), 2):
            if dist_dict[u].get(v, +Infinity) == d: # By default, no entry if disconnected. We substitute +Infinity.
                sameDistPairs.append(Set([u,v]))
        if len(sameDistPairs) >= 2:
            if not(Set(sameDistPairs) == Set(auto_group.orbit(sameDistPairs[1], action = "OnSets"))):
                return False
    return True
```

**Comment by yirkajk** [comment]
@math1um and I decided the degree-transitive definition implies the property for non-disjoint (a,b) and (u,v), so no need to make the code any more complex.
I committed changes to fix the problems he discovered.

Still need to fix the async issue. It might be a few days before I get to it.
One note from an email with Nico: the multiprocessing in gt_precomputed_database.sage is only for timeout, not for parallelism.
So, we'll have to decide what to change: is_distance_transitive or update_property_database.

**Comment by nvcleemp** [comment]
We might also try to construct a minimal example illustrating the error, and then ask on the sage-dev mailing list whether somebody knows what we are doing wrong. Might be that there is a simple solution which lets us keep both functions.

**Comment by nvcleemp** [comment]
I also think that in your implementation it would be sufficient to check whether the two sets have the same size. This might be more efficient than checking whether the sets are actually the same. (Since one contains all pairs at distance _d_ and the other only contains pairs at distance _d_, you have equality if the number of items is the same.)

**Comment by yirkajk** [comment]
This module is mentioned near the end of the traceback I posted above: https://github.com/sagemath/sagelib/blob/master/sage/interfaces/expect.py
There's a block comment in there:
> # The subprocess is a shared resource.  In a multi-threaded
> # environment, there would have to be a lock to control access to the
> # subprocess.  Fortunately, Sage does not use Python threads.
> ...

So, it seems the problem is that `update_property_database` uses the _python_ module `multiprocessing`, which this module admittedly doesn't work with.

I'll investigate whether sage has some other options for timing we can use instead of `multiprocessing`.
